### ISSUE TITLE
L'écran de confirmation de la newsletter est difficile à lire

### ISSUE THREAD

**Issue by oncletom** [noeems/estcequecestdutravail.xyz#2]
(blanc sur vert clair)

<img width="803" alt="screen shot 2018-03-18 at 19 27 11" src="https://user-images.githubusercontent.com/138627/37570031-6758e978-2ae2-11e8-8bb7-3f45c8ea6662.png">

**Comment by noeems** [comment]
![screen shot 2018-03-19 at 09 43 42](https://user-images.githubusercontent.com/17898447/37588405-0decaa6e-2b5a-11e8-87e4-90c70e7d0e05.png)
Modifé ! 
J'en ai profité pour mettre à jour le texte. 👍
