### ISSUE TITLE
Activer HTTPS en changeant les enregistrements DNS

### ISSUE THREAD

**Issue by oncletom** [noeems/estcequecestdutravail.xyz#3]
On peut avoir le site en HTTPS depuis hier : https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

Pour ça, il faut changer les enregistrements DNS `A` vers [ceux-là](https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider) :

    185.199.108.153
    185.199.109.153
    185.199.110.153
    185.199.111.153

**Comment by noeems** [comment]
Should be active within the next 24 hours. 🙏

**Comment by oncletom** [comment]
✅
